INSERT INTO artist (fname, mname, lname, dob, dod, country, local)
VALUES ('Vincent', null, 'van Gogh', 1853, 1890, 'France', 'n'),
('Rembrandt', 'Harmenszoon', 'van Rijn', 1606, 1669, 'Netherlands', 'n'),
('Leonardo', null, 'da Vanci', 1452, 1519, 'Italy', 'n'),
('Venture', 'Lonzo', 'Coy', 1965, null, 'United States', 'y'),
('Deborah', null, 'Gill', 1970, null, 'United States', 'y'),
('Claude', null, 'Monet', 1840, 1926, 'France', 'n'),
('Pablo', null, 'Picasso', 1904, 1973, 'Spain', 'n'),
('Michelangelo', 'di Lodovico', 'Simoni', 1475, 1564, 'Italy', 'n');

INSERT INTO artwork (title, artyear, period, arttype, artfile, artist_id)
VALUES ('Irises', 1889, 'Impressionism', 'Oil', 'irises.jpg', 'flowers', 1),
('The Starry Night', 1889, 'Post-Impressionism', 'Oil', 'starrynight.jpg', 'blue, landscape', 1),
('Sunflowers', 1888, 'Post-Impressionism', 'Oil', 'sunflowers.jpg', 'flowers', 1),
('Night Watch', 1642, 'Baroque', 'Oil', 'nightwatch.jpg', 'girl, people, battle', 2),
('Storm on the Sea of Galilee', 1633, 'Dutch Golden Age', 'Oil', 'stormgalilee.jpg', 'boat, water, people, Christ', 2),
('Head of a Woman', 1508, 'High Renaissance', 'Oil', 'headwoman.jpg', 'girl, people', 3),
('Last Supper', 1498, 'Renaissance', 'Tempra', 'lastsupper.jpg', 'food, people, Christ', 3),
('Mona Lisa', 1517, 'Renaissance', 'Oil', 'monalisa.jpg', 'girl, people', 3),
('Hilllside Stream', 2005, 'Modern', 'Oil', 'hillsidestream.jpg', 'water, landscape', 4),
('Old Barn', 1992, 'Modern', 'Oil', 'oldbarn.jpg', 'landscape', 4),
('Beach Baby', 1999, 'Modern', 'Watercolor', 'beachbaby.jpg', 'water, people, baby', 5),
('Old Guitarist', 1904, 'Modern', 'Oil', 'guitarist.jpg', 'blue, people', 5);

INSERT INTO keyword (keyword)
VALUES ('flowers'),
('blue'),
('landscape'),
('girl'),
('people'),
('battle'),
('boat'),
('water'),
('Christ'),
('food'),
('baby');

INSERT INTO artwork_has_keyword (artwork_id, keyword_id)
VALUES (1, 1),
(2, 2),
(2, 3),
(3, 1),
(4, 4),
(4, 5),
(4, 6),
(5, 7),
(5, 8),
(5, 5),
(5, 9),
(6, 4),
(7, 10),
(7, 5),
(7, 10),
(7, 9),
(8, 4),
(8, 5),
(9, 8),
(9, 3),
(10, 3),
(11, 8),
(11, 5),
(11, 11),
(12, 1),
(12, 3),
(12, 5),
(13, 2),
(13, 5);